name: Hotfix Release

on:
  pull_request:
    branches: [ "hotfix" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build AdventureWorks DACPAC
        run: msbuild AdventureWorks\AdventureWorks.sqlproj
      - name: Deploy DACPAC
        run: sqlpackage.exe /SourceFile:"AdventureWorks\bin\debug\AdventureWorks.dacpac" /action:publish /TargetConnectionString:"Server=localhost;Database=AWTest;Integrated Security=SSPI;Encrypt=false"
      - uses: actions/upload-artifact@v3
        with:
          name: AdventureWorks
          path: AdventureWorks/**/AdventureWorks.dacpac
  deploytoTest:
    runs-on: self-hosted
    environment: Test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: AdventureWorks
          path: ./AdventureWorks
      - name: Deploy DACPAC
        run: sqlpackage.exe /SourceFile:".\AdventureWorks\AdventureWorks.dacpac" /action:publish /TargetConnectionString:"Server=localhost;Database=AWTest;Integrated Security=SSPI;Encrypt=false"
