name: Deploy to Test

on:
  pull_request:
    branches: [ "test" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build AdventureWorks DACPAC
        run: |
          set-executionPolicy Bypass
          msbuild AdventureWorks\AdventureWorks.sqlproj
      - name: Deploy DACPAC
        uses: Azure/run-sqlpackage-action@v1.0.0
        with:
           action: 'Publish'
           sourcepath: DevIntersection/AdventureWorks/bin/debug/AdventureWorks.dacapc
           connection-string: 'Server=localhost;Database=AWTest;Integrated Security=SSPI;Encrypt=false'
