name: Deploy to Test

on:
  pull_request:
    branches: [ "test" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build AdventureWorks DACPAC
        run: |
          set-executionPolicy Bypass
          msbuild AdventureWorks\AdventureWorks.sqlproj
      - name: DeployDACPAC
        run: '"c:\Program Files\Microsoft SQL Server\160\DAC\bin\sqlpackage.exe" /SourceFile:"DevIntersection\AdventureWorks\bin\debug\AdventureWorks.dacpac" /action:publish /TargetConnectionString:"Server=localhost;Database=AWTest;Integrated Security=SSPI;Encrypt=false"'
