name: Deploy to Test

on:
  pull_request:
    branches: [ "test" ]

  workflow_dispatch:
jobs:
 buildCode:
  name: Build SQL Projects
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v3
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.1

  - name: Build AdventureWorks DACPAC
    run: msbuild AdventureWorks\AdventureWorks.sqlproj
  - name: Upload a Build Artifact
    uses: actions/upload-artifact@v3.1.3
    with:
      name: AdventureWorks
      # A file, directory or wildcard pattern that describes what to upload
      path: DevIntersection\AdventureWorks\bin\Debug\AdventureWorks.dacpac

  
