name: Deploy to Test

on:
  pull_request:
    branches: [ "test" ]

  workflow_dispatch:
jobs:
 buildCode:
  name: Build SQL Projects
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v3

  - uses: azure/sql-action@v2.2
    with:
      connection-string: "server=localhost;database=AWTest;Integrated Security=SSPI;"
      action: publish
      path: './AdventureWorks\AdventureWorks.sqlproj'
